### ISSUE TITLE
FileNotFoundError with open '/scripts/locust.config.json'

### ISSUE THREAD

**Issue by JuanYyo** [sernst/locusts#4]
Hi,

I'm having that error when trying to create a docker container.

$docker run -it --rm -v scripts:/scripts     swernst/locusts     --master-host=127.0.0.1
Traceback (most recent call last):
  File "/run.py", line 79, in <module>
    run()
  File "/run.py", line 66, in run
    args = parse()
  File "/run.py", line 12, in parse
    with open('/scripts/locust.config.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/scripts/locust.config.json'

Regards,

Juan.

**Comment by naughtron** [comment]
have you added a `locust.config.json` to your /scripts/ directory? 

at a minimum in there you will need a: 

locustfile.py
locust.config.json

as an example here is what my initial project /scripts/ dir looks like: 
```
-rw-r--r--  1 naughtron  staff    98 Apr 11 14:19 locust.config.json
-rw-r--r--  1 naughtron  staff  1379 Apr 11 14:25 locustfile.py
```
